spring:
  application:
    name: user

  # Postgres sql db configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/liora_user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: npathumdilhara@gmail.com
    password: kivttohiixvteqyn

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 0

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret-key: YTRmN2M5YjJlODNkNmYxYTdiOWQwYzRlNWYyYThkM2I=
    expiration-time: 3600000