spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/api/v1/user/**

# Defining as a eureka client
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

